import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * Daily reconciliation report for institutional clients.
 * Generated automatically or on-demand for accounting and compliance.
 */
@Entity('reconciliation_reports')
@Index(['institutionalClientId', 'reportDate'])
@Index(['reportDate', 'status'])
export class ReconciliationReport {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid' })
  institutionalClientId: string;

  /** The business date the report covers */
  @Column({ type: 'date' })
  reportDate: string;

  /** Report type */
  @Column({ type: 'varchar', default: 'DAILY' })
  reportType: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'CUSTOM';

  /** Total number of trades in the period */
  @Column({ type: 'int', default: 0 })
  totalTrades: number;

  /** Total buy volume */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  totalBuyVolume: number;

  /** Total sell volume */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  totalSellVolume: number;

  /** Net P&L for the period */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  netPnl: number;

  /** Total fees incurred */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  totalFees: number;

  /** Opening balance (quote currency) */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  openingBalance: number;

  /** Closing balance (quote currency) */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  closingBalance: number;

  /** Balance discrepancy (closing - opening + net flows) */
  @Column('decimal', { precision: 24, scale: 8, default: 0 })
  discrepancy: number;

  /** Whether the report has been reconciled (no discrepancies) */
  @Column({ default: false })
  isReconciled: boolean;

  /** Report generation status */
  @Column({ type: 'varchar', default: 'PENDING' })
  status: 'PENDING' | 'GENERATING' | 'COMPLETED' | 'FAILED';

  /** Error message if generation failed */
  @Column({ type: 'text', nullable: true })
  error?: string;

  /** Path to the generated report file (CSV / PDF) */
  @Column({ nullable: true })
  filePath?: string;

  /** Generated by (user ID or 'SYSTEM') */
  @Column({ type: 'varchar', default: 'SYSTEM' })
  generatedBy: string;

  /** Additional metadata as JSON string */
  @Column({ type: 'text', nullable: true })
  metadata?: string;

  @CreateDateColumn()
  createdAt: Date;
}
