export enum NotificationEventType {
  // Order events
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_FILLED = 'ORDER_FILLED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_PARTIALLY_FILLED = 'ORDER_PARTIALLY_FILLED',

  // Trade events
  TRADE_EXECUTED = 'TRADE_EXECUTED',

  // Deposit events
  DEPOSIT_RECEIVED = 'DEPOSIT_RECEIVED',
  DEPOSIT_CONFIRMED = 'DEPOSIT_CONFIRMED',
  DEPOSIT_FAILED = 'DEPOSIT_FAILED',

  // Withdrawal events
  WITHDRAWAL_COMPLETED = 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_CONFIRMED = 'WITHDRAWAL_CONFIRMED',
  WITHDRAWAL_FAILED = 'WITHDRAWAL_FAILED',

  // KYC / Compliance events
  KYC_STATUS_CHANGE = 'KYC_STATUS_CHANGE',

  // Margin / Risk events
  LIQUIDATION = 'LIQUIDATION',
  MARGIN_CALL = 'MARGIN_CALL',
  POSITION_LIQUIDATED = 'POSITION_LIQUIDATED',

  // Other events
  PRICE_ALERT = 'PRICE_ALERT',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  SECURITY_ALERT = 'SECURITY_ALERT',
}
