export enum NotificationEventType {
  ORDER_FILLED = 'ORDER_FILLED',
  TRADE_EXECUTED = 'TRADE_EXECUTED',
  LIQUIDATION = 'LIQUIDATION',
  DEPOSIT_RECEIVED = 'DEPOSIT_RECEIVED',
  PRICE_ALERT = 'PRICE_ALERT',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  WITHDRAWAL_COMPLETED = 'WITHDRAWAL_COMPLETED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  MARGIN_CALL = 'MARGIN_CALL',
  POSITION_LIQUIDATED = 'POSITION_LIQUIDATED',
}
